<?php

namespace Database\Seeders;

use App\Models\Repo;
use App\Models\Repo_tags;
use Illuminate\Database\Seeder;

class GlobalResearchOutputsSeeder extends Seeder
{
    public function run(): void
    {
        $publications = [
            [
                'title'        => 'Hamburg Declaration on Responsible Artificial Intelligence (AI) for the Sustainable Development Goals (SDGs)',
                'description'  => 'UNDP',
                'publish_date' => '2025-06-02',
                'data_link'    => 'https://www.bmz-digital.global/wp-content/uploads/2025/06/250603_Hamburg_Declaration.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Sustainable Development'],
            ],
            [
                'title'        => 'Global Assessment of Responsible AI in Cities',
                'description'  => 'UN-Habitat, IDRC',
                'publish_date' => '2024-01-01',
                'data_link'    => 'https://unhabitat.org/sites/default/files/2024/08/global_assessment_of_responsible_ai_in_cities_21082024.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['City Resilience'],
            ],
            [
                'title'        => 'A Nordic initiative for Research and Innovation on Responsible and Ethical Use of Artificial Intelligence',
                'description'  => 'NordForsk',
                'publish_date' => '2024-05-08',
                'data_link'    => 'https://norden.diva-portal.org/smash/get/diva2:1856812/FULLTEXT02',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Ethics', 'Resesarch', 'Responsible AI', 'National Policies'],
            ],
            [
                'title'        => 'ASEAN Responsible AI Roadmap (2026-2030)',
                'description'  => 'USAID,  ASEAN',
                'publish_date' => '2024-05-01',
                'data_link'    => 'https://asean.org/book/asean-responsible-ai-roadmap-2025-2030/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Responsible AI', 'Infrastructures', 'National Policies', 'Policy'],
            ],
            [
                'title'        => 'Responsible AI Readiness Index (RARI): A Tool for Policy Makers and Regulators to Quantify the Progress and Track the Impact of Responsible AI ',
                'description'  => 'Access Partnership',
                'publish_date' => '2024-04-01',
                'data_link'    => 'https://cdn.accesspartnership.com/wp-content/uploads/2024/04/Responsible-AI-Readiness-Index-RARI-2.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Responsible AI', 'Policy', 'Artificial Intelligence', 'Data Governance'],
            ],
            [
                'title'        => 'Recommendation on the Ethics of Artificial Intelligence',
                'description'  => 'UNESCO',
                'publish_date' => '2022-01-01',
                'data_link'    => 'https://unesdoc.unesco.org/ark:/48223/pf0000381137',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Ethics', 'Data', 'Economy', 'Gender'],
            ],
            [
                'title'        => 'AI Governance International Evaluation Index (AGILE Index) 2025',
                'description'  => 'Global AI Governance Observatory',
                'publish_date' => '2025-07-01',
                'data_link'    => 'https://arxiv.org/pdf/2507.11546',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Infrastructures', 'Gender', 'National Policies'],
            ],
            [
                'title'        => 'Africa AI Policy Tool',
                'description'  => 'African Observatory on Responsible Artificial Inelligence',
                'publish_date' => null,
                'data_link'    => 'https://www.globalcenter.ai/aorai/africa-policy-tool',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Regional', 'National Policies'],
            ],
            [
                'title'        => 'Annual Report 2024-2025',
                'description'  => 'Global Center on AI Governance',
                'publish_date' => '2025-01-01',
                'data_link'    => 'https://www.globalcenter.ai/annual-reports/2024-25.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Regional', 'Education', 'Resesarch', 'Gender', 'AI Ethics', 'Policy'],
            ],
            [
                'title'        => 'Guidelines on the Responsible Implementation of Artificial Intelligence Systems in Journalism',
                'description'  => 'Council of Europe',
                'publish_date' => '2023-11-30',
                'data_link'    => 'https://rm.coe.int/cdmsi-2023-014-guidelines-on-the-responsible-implementation-of-artific/1680adb4c6',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Access to Knowledge', 'Policy'],
            ],
            [
                'title'        => 'Guidance for Generative AI in Education and Research',
                'description'  => 'UNESCO',
                'publish_date' => '2023-01-01',
                'data_link'    => 'https://unesdoc.unesco.org/ark:/48223/pf0000386693',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Education', 'Resesarch', 'AI Ethics'],
            ],
            [
                'title'        => 'AI Competency Framework for Teachers',
                'description'  => 'UNESCO',
                'publish_date' => '2024-01-01',
                'data_link'    => 'https://unesdoc.unesco.org/ark:/48223/pf0000391104',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Education', 'AI Ethics'],
            ],
            [
                'title'        => 'The Impact of Artificial Intelligence on Democracy, Human Rights and the Rule of Law',
                'description'  => 'Inter-Parliamentary Union',
                'publish_date' => '2024-10-17',
                'data_link'    => 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.ipu.org/file/20061/download&ved=2ahUKEwiwj7KVwaSUAxUIxgIHHdldAZ4QFnoECBkQAQ&usg=AOvVaw1gte6s_piiQpVSmzpulTDU ',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Policy', 'Gender', 'Economy', 'Education', 'Resesarch', 'Conference Proceeding'],
            ],
            [
                'title'        => 'AI Competency Framework for Students',
                'description'  => 'UNESCO',
                'publish_date' => '2024-01-01',
                'data_link'    => 'https://www.cedefop.europa.eu/files/unesco_ai_competency_framework_for_students_.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Education', 'AI Technologies', 'AI Ethics'],
            ],
            [
                'title'        => 'Factsheet: Artificial Intelligence and the Women, Peace and Security Agenda',
                'description'  => 'UNIDIR',
                'publish_date' => '2025-09-02',
                'data_link'    => 'https://unidir.org/publication/factsheet-artificial-intelligence-and-the-women-peace-and-security-agenda/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Gender', 'Security', 'Responsible AI'],
            ],
            [
                'title'        => 'Artificial Intelligence in the Military Domain and Its Implications for International Peace and Security: An Evidence-Based Road Map for Future Policy Action',
                'description'  => 'UNIDIR',
                'publish_date' => '2025-07-03',
                'data_link'    => 'https://unidir.org/publication/artificial-intelligence-in-the-military-domain-and-its-implications-for-international-peace-and-security-an-evidence-based-road-map-for-future-policy-action/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Security', 'AI Technologies'],
            ],
            [
                'title'        => 'G7 Tolkit for Artificial Intelligence in the Public Sector',
                'description'  => 'UNESCO, OECD',
                'publish_date' => '2024-10-15',
                'data_link'    => 'https://unesdoc.unesco.org/ark:/48223/pf0000391566',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Public', 'Policy', 'Infrastructures'],
            ],
            [
                'title'        => 'Introduction to Responsible AI Innovation',
                'description'  => 'INTERPOL, UNICRI',
                'publish_date' => '2024-02-01',
                'data_link'    => 'https://ai-lawenforcement.org/sites/default/files/2025-03/Intro_Resp_AI_Innovation_Mar25.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Security', 'AI Technologies'],
            ],
            [
                'title'        => 'Principles for Responsible AI Innovation',
                'description'  => 'INTERPOL, UNICRI',
                'publish_date' => '2024-02-01',
                'data_link'    => 'https://ai-lawenforcement.org/sites/default/files/2025-03/Principles_Resp_AI_Innovation_Mar25.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Security', 'AI Technologies'],
            ],
            [
                'title'        => 'Organizational Roadmap',
                'description'  => 'INTERPOL, UNICRI',
                'publish_date' => '2024-02-01',
                'data_link'    => 'https://ai-lawenforcement.org/sites/default/files/2025-03/Organizational_Roadmap_Mar25.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Security', 'AI Technologies'],
            ],
            [
                'title'        => 'Advancing Responsible Development and Deployment of Generative AI',
                'description'  => 'UNHRC',
                'publish_date' => null,
                'data_link'    => 'https://www.ohchr.org/sites/default/files/documents/issues/business/b-tech/advancing-responsible-development-and-deployment-of-GenAI.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Data Governance', 'Busines Development', 'Economy', 'Policy'],
            ],
            [
                'title'        => 'Responsible AI and Human Rights: An Overview of Company Practices - Supplement to B-Tech’s Foundational Paper on the Responsible Development and Deployment of Generative AI',
                'description'  => 'UNHRC',
                'publish_date' => '2023-11-01',
                'data_link'    => 'https://www.ohchr.org/sites/default/files/documents/issues/business/b-tech/overview-human-rights-and-responsible-AI-company-practice.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Data Governance', 'Busines Development', 'Economy', 'Policy'],
            ],
            [
                'title'        => 'Political Declaration on Responsible Military Use of Artificial Intelligence and Autonomy',
                'description'  => 'US State Department',
                'publish_date' => '2023-02-01',
                'data_link'    => 'https://www.state.gov/wp-content/uploads/2023/10/Latest-Version-Political-Declaration-on-Responsible-Military-Use-of-AI-and-Autonomy.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['National Policies', 'Security'],
            ],
            [
                'title'        => 'Artificial intelligence in the military domain and its implications for international peace and security',
                'description'  => 'UNGA',
                'publish_date' => '2024-12-24',
                'data_link'    => 'https://digitallibrary.un.org/record/4071348?v=pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Policy', 'Security'],
            ],
            [
                'title'        => 'The Impact of Artificial Intelligence on Regional Security, Threat Perceptions and the Middle East WMD-Free Zone',
                'description'  => 'UNIDIR',
                'publish_date' => '2025-02-07',
                'data_link'    => 'https://unidir.org/publication/the-impact-of-artificial-intelligence-on-regional-security-threat-perceptions-and-the-middle-east-wmd-free-zone/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Policy', 'Security', 'Data Governance', 'Regional', 'Governing Responsible AI & Data in the MENA Region'],
            ],
            [
                'title'        => 'Exploring the AI–ICT Security Nexus',
                'description'  => 'UNIDIR',
                'publish_date' => '2024-01-01',
                'data_link'    => 'https://unidir.org/wp-content/uploads/2024/12/UNIDIR_ICT_Intrusion_Path_A4_Final.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['ICTs', 'AI Technologies', 'Data Governance', 'Security'],
            ],
            [
                'title'        => 'The Interpretation and Application of International Humanitarian Law in Relation to Lethal Autonomous Weapon Systems',
                'description'  => 'UNIDIR',
                'publish_date' => '2025-03-06',
                'data_link'    => 'https://unidir.org/publication/the-interpretation-and-application-of-international-humanitarian-law-in-relation-to-lethal-autonomous-weapon-systems/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Security'],
            ],
            [
                'title'        => 'Artificial Intelligence in the Military Domain and its Implications for International Peace and Security',
                'description'  => 'UNIDIR',
                'publish_date' => '2025-07-03',
                'data_link'    => 'https://unidir.org/publication/artificial-intelligence-in-the-military-domain-and-its-implications-for-international-peace-and-security-an-evidence-based-road-map-for-future-policy-action/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Security', 'Responsible AI'],
            ],
            [
                'title'        => 'Governance of Artificial Intelligence in the Military Domain: A Multi-stakeholder Perspective on Priority Areas',
                'description'  => 'UNIDIR',
                'publish_date' => '2024-09-05',
                'data_link'    => 'https://unidir.org/publication/governance-of-artificial-intelligence-in-the-military-domain-a-multi-stakeholder-perspective-on-priority-areas/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Security', 'Responsible AI'],
            ],
            [
                'title'        => 'Draft Guidelines for the Development of a National Strategy on AI in Security and Defence: Apolicy Brief',
                'description'  => 'UNIDIR',
                'publish_date' => '2024-10-24',
                'data_link'    => 'https://unidir.org/publication/draft-guidelines-for-the-development-of-a-national-strategy-on-ai-in-security-and-defence/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Policy', 'National Policies', 'Security'],
            ],
            [
                'title'        => 'Does Military AI Have Gender? Understanding Bias and Promoting Ethical Approaches in Military Applications of AI',
                'description'  => 'UNIDIR',
                'publish_date' => '2021-12-07',
                'data_link'    => 'https://unidir.org/publication/does-military-ai-have-gender-understanding-bias-and-promoting-ethical-approaches-in-military-applications-of-ai/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Gender', 'AI Technologies', 'Security'],
            ],
            [
                'title'        => 'AI and International Security: Understanding the Risks and Paving the Path for Confidence-Building Measures',
                'description'  => 'UNIDIR',
                'publish_date' => '2023-10-12',
                'data_link'    => 'https://unidir.org/publication/ai-and-international-security-understanding-the-risks-and-paving-the-path-for-confidence-building-measures/',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Security', 'Policy'],
            ],
            [
                'title'        => 'Establishing responsible use of AI guidelines: a comprehensive case study for healthcare institutions',
                'description'  => 'npj Digital Medicine',
                'publish_date' => '2024-11-30',
                'data_link'    => 'https://www.nature.com/articles/s41746-024-01300-8',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Health', 'Policy'],
            ],
            [
                'title'        => 'Guidance on AI and children',
                'description'  => 'UNICEF',
                'publish_date' => '2025-12-01',
                'data_link'    => 'https://www.unicef.org/innocenti/reports/policy-guidance-ai-children',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Ethics', 'Data'],
            ],
            [
                'title'        => 'Novissi Togo:  Harnessing Artificial Intelligence to Deliver Shock-Responsive Social Protection',
                'description'  => 'World Bank',
                'publish_date' => '2023-09-01',
                'data_link'    => 'https://documents1.worldbank.org/curated/en/099751009222330502/pdf/IDU0e83f857301ff1047bf082710a8d21ddf42c3.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Economic Growth', 'AI Technologies', 'Artificial Intelligence and Inclusion', 'Data Governance', 'Vulnerable Communities'],
            ],
            [
                'title'        => 'The Use of Advanced Technology in Job Matching Platforms: Recent Examples from Public Agencies',
                'description'  => 'World Bank',
                'publish_date' => '2023-05-01',
                'data_link'    => 'https://thedocs.worldbank.org/en/doc/ceb5c5792ad0d874e9b1c3cc71362f46-0460012023/original/Digital-Job-Matching-Platforms-S4YE-Draft-Note-for-Discussion.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Economy', 'Vulnerable Communities', 'Young Population', 'Youth Entrepreneurship'],
            ],
            [
                'title'        => 'Cracking the Credit Code: Alternative Data and AI for Financial Inclusion',
                'description'  => 'IFC',
                'publish_date' => '2026-05-01',
                'data_link'    => 'https://www.ifc.org/content/dam/ifc/doc/2026/cracking-the-credit-code-alternative-data-and-ai-for-financial-inclusion.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Economy', 'Inclusion', 'Data', 'Gender'],
            ],
            [
                'title'        => 'Governing Artificial Intelligence Responsibility in Low-to-Middle Income Countries: Pathways to Sustainable Development',
                'description'  => 'World Bank',
                'publish_date' => '2024-01-01',
                'data_link'    => 'https://heinonline.org/HOL/P?h=hein.journals/calwi54&i=433',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Sustainable Development', 'Data Governance', 'Responsible AI', 'Vulnerable Communities'],
            ],
            [
                'title'        => 'Responsible Artificial Intelligence Efforts in the Global South: A Global Futures Bulletin from the Igarapé Institute and New America',
                'description'  => 'Igarapé Institute, New America',
                'publish_date' => '2024-01-01',
                'data_link'    => 'https://igarape.org.br/wp-content/uploads/2024/01/Global-Futures-Bulletin-Responsible-Artificial-Intelligence-Efforts-In-the-Global-South.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Responsible AI', 'Policy'],
            ],
            [
                'title'        => 'AI’s Global South Pivot: Equity, Ethics and Ecology',
                'description'  => 'Centre for International Governance Innovation',
                'publish_date' => '2026-02-01',
                'data_link'    => 'https://www.cigionline.org/static/documents/Policy_Brief_No._225_Maheshwari.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Ethics', 'Environment', 'Inclusion'],
            ],
            [
                'title'        => 'AI and the Global South: Exploring the Role of Civil Society in AI Decision-Making',
                'description'  => 'Care International',
                'publish_date' => '2024-09-01',
                'data_link'    => 'https://careinternationaluk.ams3.cdn.digitaloceanspaces.com/media/documents/AIthe_Global_South_Exploring_the_Role_of_Civil_Society_in_AI_Decision-Making.pdf',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Responsible AI', 'Inclusion'],
            ],
            [
                'title'        => 'Responsible artificial intelligence in agriculture requires systemic understanding of risks and externalities',
                'description'  => 'nature machine intelligence',
                'publish_date' => '2022-02-23',
                'data_link'    => 'https://www.nature.com/articles/s42256-022-00440-4',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Inclusion', 'Responsible AI'],
            ],
            [
                'title'        => 'Artificial intelligence for strengthening healthcare systems in low- and middle-income countries: a systematic scoping review',
                'description'  => 'npj Digital Medicine',
                'publish_date' => '2022-10-28',
                'data_link'    => 'https://www.nature.com/articles/s41746-022-00700-y',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Health', 'Algorithm', 'Resesarch'],
            ],
            [
                'title'        => 'Policy brief: Powering Inclusion: Artificial Intelligence and Assistive Technology',
                'description'  => 'UCL, Global Disabilit Innovation Hub',
                'publish_date' => '2021-03-01',
                'data_link'    => 'https://cdn.disabilityinnovation.com/uploads/images/AIATPolicyBrief_ToPublish.pdf?v=1619774523',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Inclusion', 'Policy', 'AI Technologies'],
            ],
            [
                'title'        => 'How is AI Disrupting Teachers’ Roles in Low- and Middle- Income Countries?',
                'description'  => 'AI Observatory, EdTech Hub',
                'publish_date' => '2026-04-30',
                'data_link'    => 'https://docs.edtechhub.org/lib/UXT3K2K3/download/69XHNFTM',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Education', 'AI Ethics'],
            ],
            [
                'title'        => 'Learners in the Age of AI',
                'description'  => 'AI Observatory, EdTech Hub',
                'publish_date' => '2026-03-01',
                'data_link'    => 'https://docs.edtechhub.org/lib/M5E9SEKI/download/FSIDNPBU',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Education', 'AI Ethics'],
            ],
            [
                'title'        => 'How Is AI Being Used by Education Ministries to Improve Service Delivery in Low- and Middle-Income Countries?',
                'description'  => 'AI Observatory, EdTech Hub',
                'publish_date' => '2025-01-01',
                'data_link'    => 'https://docs.edtechhub.org/lib/FPN46G82/download/YXDAY9G9',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Education', 'AI Ethics', 'National Policies'],
            ],
            [
                'title'        => 'Deploying medical AI in low-resource settings: a scoping review of challenges and strategies',
                'description'  => 'Frontiers in Digital Health',
                'publish_date' => '2026-04-01',
                'data_link'    => 'https://www.frontiersin.org/journals/digital-health/articles/10.3389/fdgth.2026.1743634/full?utm_source=chatgpt.com',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['Health', 'AI Technologies'],
            ],
            [
                'title'        => 'Challenges and Opportunities for Data Sharing Related to Artificial Intelligence Tools in Health Care in Low- and Middle-Income Countries: Systematic Review and Case Study From Thailand',
                'description'  => 'Journal of Medical Internet Research',
                'publish_date' => '2025-02-04',
                'data_link'    => 'https://www.jmir.org/2025/1/e58338/PDF',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['National Policies', 'Health', 'Data Governance'],
            ],
            [
                'title'        => 'Generative AI for Health in Low & Middle Income Countries',
                'description'  => 'Stanford Center for Digital Health',
                'publish_date' => '2025-02-01',
                'data_link'    => 'https://indd.adobe.com/view/65c53fb2-708f-4d24-a389-52a67e633e66',
                'is_global'    => true,
                'is_our_work'  => false,
                'image'        => '',
                'tags'         => ['AI Technologies', 'Health', 'Data'],
            ],
        ];

        foreach ($publications as $data) {
            $tagNames = $data['tags'];
            unset($data['tags']);

            if (Repo::where('title', $data['title'])->exists()) {
                continue;
            }

            $repo = Repo::create($data);

            foreach ($tagNames as $name) {
                $tag = Repo_tags::firstOrCreate(['name' => $name]);
                $repo->tags()->attach($tag->id);
            }
        }
    }
}
