<?php

namespace Database\Seeders;

use App\Models\PwMenaPublication;
use Illuminate\Database\Seeder;

class PwMenaPublicationSeeder extends Seeder
{
    public function run()
    {
        $publications = [
            // ── REPORTS ──────────────────────────────────────────────────────────
            [
                'type'      => 'report',
                'title'     => 'Cloudwork: Social Protection and Inclusion in the Digital Economy in Egypt',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 1,
            ],
            [
                'type'      => 'report',
                'title'     => 'Platform work, social protection and representation: a case of delivery workers in Egypt',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => '/docs/egypt/egypt-delivery-workers-policy-paper.pdf',
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 2,
            ],
            [
                'type'      => 'report',
                'title'     => 'Social Security Provisions for Workers in the Gig Economy: A Focus on Egypt',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 3,
            ],
            [
                'type'      => 'report',
                'title'     => 'Reaction Note on the Draft Labor Law Regarding the New Forms of Labor',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 4,
            ],
            [
                'type'      => 'report',
                'title'     => 'New Work, Data and Inclusion in the Digital Economy: Case Study Jordan',
                'ar_title'  => 'العمل الجديد - عمال المنصات الرقمية - حالة الأردن',
                'tag'       => 'Jordan',
                'link_en'   => '/docs/jordan/jordan-platform-workers-policy-paper-en.pdf',
                'link_ar'   => '/docs/jordan/jordan-platform-workers-policy-paper-ar.pdf',
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 5,
            ],
            [
                'type'      => 'report',
                'title'     => 'The perils of digital work in Lebanon: lessons from taxi and delivery workers',
                'ar_title'  => null,
                'tag'       => 'Lebanon',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 6,
            ],
            [
                'type'      => 'report',
                'title'     => 'New Work: Platform Workers - Case of Lebanon',
                'ar_title'  => 'العمل الجديد - عمال المنصات الرقمية - حالة لبنان',
                'tag'       => 'Lebanon',
                'link_en'   => '/docs/lebanon/lebanon-platform-workers-report-en.pdf',
                'link_ar'   => '/docs/lebanon/lebanon-platform-workers-report-ar.pdf',
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 7,
            ],
            [
                'type'      => 'report',
                'title'     => 'Platform Workers: a Morocco Case Study',
                'ar_title'  => 'عمال المنصات الرقمية: دراسة حالة المغرب',
                'tag'       => 'Morocco',
                'link_en'   => '/docs/morocco/morocco-platform-workers-policy-paper-en.pdf',
                'link_ar'   => '/docs/morocco/morocco-platform-workers-policy-paper-ar.pdf',
                'link_fr'   => '/docs/morocco/morocco-platform-workers-policy-paper-fr.pdf',
                'external_link' => null,
                'sort_order' => 8,
            ],
            [
                'type'      => 'report',
                'title'     => "New Forms of Work, Old Forms of Exploitation: Tunisia's Platform and Informal Economies",
                'ar_title'  => 'أشكال جديدة من العمل، أشكال قديمة من الاستغلال: تحليل اقتصاد المنصات في تونس',
                'tag'       => 'Tunisia',
                'link_en'   => '/docs/tunisia/tunisia-platform-workers-policy-paper-en.pdf',
                'link_ar'   => '/docs/tunisia/tunisia-platform-workers-policy-paper-ar.pdf',
                'link_fr'   => '/docs/tunisia/tunisia-platform-workers-policy-paper-fr.pdf',
                'external_link' => null,
                'sort_order' => 9,
            ],
            [
                'type'      => 'report',
                'title'     => 'Fairwork Egypt 2021: Towards Decent Work in a Highly Informal Economy',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 10,
            ],
            [
                'type'      => 'report',
                'title'     => 'Domestic Platform Work in the Middle East and North Africa',
                'ar_title'  => null,
                'tag'       => 'MENA',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 11,
            ],
            [
                'type'      => 'report',
                'title'     => "Fairwork Egypt 2022: Platform Workers Amidst Egypt's Economic Crisis",
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 12,
            ],
            [
                'type'      => 'report',
                'title'     => 'New Work: Platform Workers in Egypt 2025',
                'ar_title'  => 'العمل الجديد: عمال المنصات الرقمية في مصر 2025',
                'tag'       => 'Egypt',
                'link_en'   => '/docs/egypt/egypt-2025-platform-workers-policy-paper-en.pdf',
                'link_ar'   => '/docs/egypt/egypt-2025-platform-workers-policy-paper-ar.pdf',
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 13,
            ],

            // ── POLICY BRIEFS ────────────────────────────────────────────────────
            [
                'type'      => 'brief',
                'title'     => 'Social protection and representation for delivery workers in Egypt',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => '/docs/egypt/egypt-delivery-workers-policy-brief.pdf',
                'sort_order' => 1,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Social Security Provisions for Workers in the Platform Economy: Policy Options with Focus on Egypt',
                'ar_title'  => null,
                'tag'       => 'Egypt',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 2,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Navigating the Digital Frontier: Policy Reforms for Platform Workers in Jordan',
                'ar_title'  => 'التنقل في الحدود الرقمية: إصلاحات السياسات لعمال المنصات في الأردن',
                'tag'       => 'Jordan',
                'link_en'   => '/docs/jordan/jordan-platform-workers-policy-brief-en.pdf',
                'link_ar'   => '/docs/jordan/jordan-platform-workers-policy-brief-ar.pdf',
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 3,
            ],
            [
                'type'      => 'brief',
                'title'     => "Precarious freelancing: Lebanon's grim future of work",
                'ar_title'  => null,
                'tag'       => 'Lebanon',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 4,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Policy Brief: Platform Workers - Case of Lebanon',
                'ar_title'  => 'موجز سياسات - عمال المنصات الرقمية - حالة لبنان',
                'tag'       => 'Lebanon',
                'link_en'   => '/docs/lebanon/lebanon-platform-workers-policy-brief-en.pdf',
                'link_ar'   => '/docs/lebanon/lebanon-platform-workers-policy-brief-ar.pdf',
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 5,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Improving Inclusivity in the Platform Economy',
                'ar_title'  => null,
                'tag'       => 'MENA',
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 6,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Platform Workers in Morocco: a Policy Brief',
                'ar_title'  => null,
                'tag'       => 'Morocco',
                'link_en'   => '/docs/morocco/morocco-platform-workers-policy-brief-en.pdf',
                'link_ar'   => null,
                'link_fr'   => '/docs/morocco/morocco-platform-workers-policy-brief-fr.pdf',
                'external_link' => null,
                'sort_order' => 7,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Policy Brief: Platform Workers - Case of Egypt',
                'ar_title'  => 'موجز سياسات - عمال المنصات الرقمية - حالة مصر',
                'tag'       => 'Egypt',
                'link_en'   => '/docs/egypt/egypt-platform-workers-policy-brief-en.pdf',
                'link_ar'   => '/docs/egypt/egypt-platform-workers-policy-brief-ar.pdf',
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 8,
            ],
            [
                'type'      => 'brief',
                'title'     => 'Policy Brief: Platform Workers - Case of Tunisia',
                'ar_title'  => 'موجز سياسات - عمال المنصات الرقمية - حالة تونس',
                'tag'       => 'Tunisia',
                'link_en'   => '/docs/tunisia/tunisia-platform-workers-policy-brief-en.pdf',
                'link_ar'   => '/docs/tunisia/tunisia-platform-workers-policy-brief-ar.pdf',
                'link_fr'   => '/docs/tunisia/tunisia-platform-workers-policy-brief-fr.pdf',
                'external_link' => null,
                'sort_order' => 9,
            ],

            // ── BLOG POSTS ───────────────────────────────────────────────────────
            [
                'type'      => 'blog',
                'title'     => 'Digital Platforms: New Professions in Need of Regulation',
                'ar_title'  => null,
                'tag'       => null,
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 1,
            ],
            [
                'type'      => 'blog',
                'title'     => 'New Work: Three Challenges to Protecting Millions of Young Egyptians',
                'ar_title'  => null,
                'tag'       => null,
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => 'https://menaobservatory.ai/en/blogs/64',
                'sort_order' => 2,
            ],
            [
                'type'      => 'blog',
                'title'     => 'Social Security Provisions for Workers in the Platform Economy: Policy Options with Focus on Egypt',
                'ar_title'  => null,
                'tag'       => null,
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 3,
            ],
            [
                'type'      => 'blog',
                'title'     => 'Why So Many Platform Economy Jobs are Informal',
                'ar_title'  => null,
                'tag'       => null,
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 4,
            ],
            [
                'type'      => 'blog',
                'title'     => 'The Flexibility and Desperation of Platform Work in Tunisia',
                'ar_title'  => null,
                'tag'       => null,
                'link_en'   => null,
                'link_ar'   => null,
                'link_fr'   => null,
                'external_link' => null,
                'sort_order' => 5,
            ],
        ];

        foreach ($publications as $data) {
            PwMenaPublication::firstOrCreate(
                ['title' => $data['title'], 'type' => $data['type']],
                $data
            );
        }
    }
}
