#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec "$@"
else
    # Start PHP-FPM
    service php8.2-fpm start
    
    # Keep container running
    tail -f /dev/null
fi